import React from "react";
import ReactDOM from "react-dom";
import Quotes from "./quotes";
import App from "./App";
import Triangles from "./triangles";

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
ReactDOM.render(<Triangles />, document.getElementById("triangles"));

ReactDOM.render(
    <Quotes
      heading=""
      dataText={[  
          '',
        'There’s no prize in winning other than self-satisfied loneliness',
'People don’t change when they are told what’s wrong with them...they change when they feel sufficiently supported to undertake the change they already know is due.',
'It always seems impossible until it’s done. - Nelson Mandela',
'Try not to become a man of success but rather to become a man of value. - Albert Einstein',
'Experience is simply the name we give our mistakes. - Oscar Wilde',
'Love all, trust a few, do wrong to none. - William Shakespeare',
'You miss 100 percent of the shots you never take. - Wayne Gretzky',
'Insanity: doing the same thing over and over again and expecting different results. - Albert Einstein',
'Creativity is intelligence having fun. - Albert Einstein',
'Nobody realizes that some people expend tremendous energy merely to be normal. - Albert Camus',
'The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man. - George Bernard Shaw',
'You know what potential means? It means you ain’t done shit yet - Anonymous',
'The single raindrop never feels responsible for the flood. - douglas Adams',
'The problem isn’t the problem. The problem is your attitude about the problem. - Captain Jack Sparrow',
'It is the mark of an educated mind, to entertain a thought without accepting it - Aristotle',
'But you don’t become great by trying to be great. You become great by wanting to do something, and doing it so hard that you become great in the process. - XKCD',
'Which is better; to be born good, or to overcome your evil nature through great effort? Paarthurnax',
'Stand in the ashes of a trillion dead souls and ask the ghosts if honor matter. The silence is your answer. - Javik',
'Everyone thinks they are the hero of their own story" - Handsome Jack',
'Too often we enjoy the comfort of opinion without the discomfort of thought. - JFK',
'The best time to plant a tree was 20 years ago, 2nd best time is now -no idea',
'Follow your heart, but take your brain with you',
'We can’t fix a problem if we don’t first acknowledge it',
'If you put someone on a pedestal, all they can do is look down on you',
'There is no sadder sight than a young pessimist - Mark Twain',
'Don’t take criticism from someone you wouldn’t take advice from.',
'Stupid people don’t learn from mistakes, smart people learn from their own mistakes, and wise people learn from others’ mistakes',
'the difference between sinners and saints is that every saint has a past and every sinner has a future',
'It is not our abilities that show who we truly are, it is our choices. - Albus Dumbledore',
'All those days that came and went, little did I know that they were life.',
'The consequences of anger are often greater than the causes of it',
'Feelings can’t be ignored, no matter how unjust or ungrateful they seem - Anne Frank',
'Today you, tomorrow me',
'Thoughts become perception, perception becomes reality. Alter your thoughts, alter your reality. - William James',
'Man can do what he wants but he cannot want what he wants. - Arthur Schopenhauer',
'Pretending not to be hurt isn’t the same as healing.',
'Of all the things I lost I miss my mind the most',
'Nostalgia is a toxic impulse.',
'Adversity does not build character, it reveals it.',
'Love is like war; easy to begin but very hard to stop. - H. L. Mencken',
'We judge others by their actions,but we judge ourselves by our intentions - Ian Percy',
'No person chooses evil because it is evil; they only mistakes it for happiness, the good he seeks. - Mary Shelley',
'I’m not upset that you lied to me, I’m upset that from now on I can’t believe you. - Friedrich Nietzsche',
'Out of suffering have emerged the strongest souls; the most massive characters are seared with scars. - Kahlil Gibran',
'The child who is not embraced by the village will burn it down to feel its warmth',
'Never make fun of someone if they mispronounce a word. It means they learned it by reading - Anonymous',
'When a person tells you that you hurt them, you don’t get to decide that you didn’t. -Louis CK',
'Those who can make you believe absurdities, can make you commit atrocities. - Voltaire',
'Everyone you meet always asks if you have a career, are married, or own a house as if life was some kind of grocery list. But no one ever asks you if you are happy - Heath Ledger',
'If you love someone, everything is negotiable. If you don’t, everything is a door. - Carrie Fisher',
'If you can’t intelligently argue for both sides of an issue, you don’t understand the issue well enough to argue for either.',
'One of the hardest things you will ever have to do is grieve the loss of a person who is still alive.',
'Just because you’re trash doesn’t mean you can’t do great things. It is called ’garbage can’, not ’garbage cannot’',
'A person doing evil knowing they are doing evil, has their own limits. A person doing evil believing they are doing good will destroy the world.',
'You need to learn how to heal yourself, or you will spend your life bleeding on people who didn’t cut you. – Unknown',
'I’ve never seen any life transformation that didn’t begin with the person in question finally getting tired of their own bullshit',
'You’re under no obligation to be the same person you were 5 minutes ago - Alan Watts',
'A lot of parents will do anything for their kids, except let them be themselves - Banksy',
'In a relationship, you need somebody who’s going to call you out, not somebody who’s going to let everything slide. You need somebody who doesn’t want to live without you, but can. Not somebody that is dependent, but somebody who is stronger with you. A relationship is two people, not one. Unknown',
'I find that a duck’s opinion of me is very much influenced over whether or not I have bread. - Mitch Hedberg',
'If god doesn’t like the way I live, Let him tell me, not you. - Unknown',
'“It’s silly to try to escape other people’s faults. They are inescapable. Just try to escape your own.” - Marcus Aurelius',
'“The world is a comedy to those that think, a tragedy to those that feel.” -- Horace Walpole',
'“If you are distressed by anything external, the pain is not due to the thing itself but to your estimate of it, and this you have the power to revoke at any moment.” — Marcus Aurelius',
'"Don’t do heroin, you’d love it." - Random guy at the bus stop',
'Don’t practice until you get it right, practice until you can’t get it wrong.',
'Hate is like drinking poison and hoping the other person dies.',
'Time you enjoyed wasting is not wasted time',
'Never do illegal shit while doing illegal shit.',
'If it smells everywhere you go maybe it’s you.',
'The true master is an eternal student.',
'Anger gives motivation without purpose.',
'The world is changed by your example, not by your opinion.',
'You will always meet your destiny on the path you took trying to avoid it.',
'the meaning of life is to become the person you want to be',
'When you do things right, people won’t be sure you’ve done anything at all. - God on Futurama',
'What stands in the way becomes the way.',
'Don’t cry for something that can’t cry for you',
'The greatest mistake a smart person can make, is thinking that they’re smart.',
'If they wanted to they would.',
'If you end up with a boring miserable life because you listened to your mom, your dad, your teacher, your priest, or some guy on television telling you how to do your shit, then you deserve it. – Frank Zappa',
'You don’t need motivation to do something. You just do it.',
'Don’t believe everything you think',
'Never allow someone to be your priority while allowing yourself to be their option',
'You don’t practice climbing Mount Everest by climbing Mount Everest.',
'"You can tell the size of a person by the size of the thing that makes them mad." - Adlai Stevenson',
'Knowing the path and walking the path are not the same thing.',
'Intelligence is knowing tomato is a fruit, wisdom is knowing not to put it in a fruit salad',
'If you aren’t enjoying what you’re doing why the hell are you doing it.',
'A fool takes no pleasure in understanding, but only in expressing his opinion.',
'When you talk, you are only repeating what you already know. But if you listen, you might learn something new',
'Love with your heart, and use your head for everything else',
'Be careful what you tolerate you are teaching people how to treat you',
'No good deed goes unpunished',
'Don’t be an idiot.',
'Be strong enough to be gentle.',
'When the heroes run and hide who will stay and fight? - Saitama',
'Always underpromise and overdeliver',
'Give a man a mask and he will show you his true face.',
'You could walk on water and people will say it’s because you can’t swim.',
'If you dig the best ditches, your only reward will be a bigger shovel',
'Yesterday is History, Tomorrow is a Mystery, but today is a gift. This is why it is called the "Present"',
'Why say many words when few do trick?',
'A wise man once said nothing.',
'Patience is a virtue, but patience has a limit.',
'We must all suffer from one of two pains, the pain of discipline or the pain of regret.',
'Reasons are for reasonable people.',
'Wherever you go, there you are.',
'Lead me, follow me, or get out of my way',
'Don’t let other people’s limitations become your constraints.',
'Rock bottoms will teach you the lesson mountain tops never will.',
'The Devil is in the details',
'The tallest mountain started as a stone.',
'The enemy to win against is the enemy within',
'Don’t listen when they tell you to give 110%. The most you can give is 100% and that kills you',
'Become the man that you’ll love, not the man you were meant to be.',
'You can do anything you want, as long as you accept the consequences.',
'In light of my past experience, my present circumstances, and my future hopes and dreams, what’s the wise thing to do?',
'When someone shows you who they are believe them',
'Take a gamble that love exists and do a loving act',
'When you’re in a room with someone clearly smarter than you, don’t try to show them how smart you are. Listen to them.',
'If you cannot be happy with nothing, you cannot be happy ever.',
'You accept the love you think you deserve.',
'It takes a lifetime to master a skill, so the earlier you start the longer it takes.',
'If you want to be happy you have to sometimes be egoistic.',
'"A wise man will learn more from a foolish question, than a foolish man can learn from a wise answer." -Bruce Lee',
'You know you are a smart man when all the morons turn against you.',
'Just because something is understandable, doesn’t make it acceptable',
'If you want to go fast, go alone. If you want to go far, go together.',
'If someone you love changes your life to a great enough extent, if he or she changes the person you have grown to be, if this person adds enough of his or her personal touch to the canvas that is your life, and you love the result, then you have no choice but to love this person.',
'If you zoom out far enough nothing matters. And if you stop reading there, I don’t blame you. But the next step to take is the realization that if nothing matters, then neither does that. If nothing matters, it doesn’t matter that nothing matters. But if that doesn’t matter (and if anything would matter, it would be that), then surely it can’t matter if you assign meaning to things. The Universe is a blank canvas in terms of meaning, and you are the only one with a paintbrush. The point to living is an open field on life’s questionnaire that you can fill in and erase and revise however many times you want. Doesn’t have to be big. Doesn’t have to be for anyone or anything in particular. Because if nothing matters, then anything can matter, and you get to make that call.',
'Embarrassment is the cost of entry. If you aren’t willing to look like a foolish beginner you’ll never become a graceful master.',
'It is a deep human tragedy that death is terrifying and immortality unbearable -Adrian Moore',
'Until you make the unconscious conscious, it will direct your life and you will call it fate. - Carl Jung',
'Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes. - Carl Jung',
'Everything that irritates us about others can lead us to an understanding of ourselves. - Carl Jung',
'The constant influx of negative thoughts and fears in your head are just that ... thoughts. Yet those thoughts have the power to completely consume many people.',
'"What is better - to be born good, or to overcome your evil nature through great effort?" - Paarthurnax',
'Did I ever tell you what the definition of insanity is? Insanity is doing the exact... same fucking thing... over and over again expecting... shit to change... That. Is. Crazy. The first time somebody told me that, I dunno, I thought they were bullshitting me, so, boom, I shot him. The thing is... he was right. And then I started seeing, everywhere I looked, everywhere I looked all these fucking pricks, everywhere I looked, doing the exact same fucking thing... over and over and over and over again thinking: "This time is gonna be different. No, no, no please... This time is gonna be different."',
'He who has a thousand friends has not a friend to spare, And he who has one enemy will meet him everywhere.',
'Nothing is true, everything is permitted.',
'I don’t have time to explain why I don’t have time to explain.',
'Be afraid! And then do it anyway!',
'Mi basta arrivare ad avere, senza lavorare, più soldi di quelli che un uomo onesto dovrebbe avere - Daniele Trebbi',
'Experience is a hard teacher because she gives the test first, the lesson afterward. - Vernon Law',
'You begin saving the world by saving one man at a time; all else is grandiose romanticism or politics.',
'You become what you constantly think about. Watch yourself.',
'Be the reason someone believes in good people.',
'You can’t change the people around you, but you can change the people around you. -Unknown',
'Of course I’ll hurt you. Of course you’ll hurt me. Of course we will hurt each other. But this is the very condition of existence. To become spring, means accepting the risk of winter. To become presence, means accepting the risk of absence. - Antoine de Saint-Exupéry',
'One day you will tell the story of how you’ve overcome what you’re going through now, and it will become part of someone else’s survival guide.',
'"Care about what other people think, and you will always be their prisoner." – Lao Tzu',
'Pain doesn’t tell you when you ought to stop. Pain is the little voice in your head that tries to hold you back because it knows if you continue you will change. - Kobe Bryant',
'Make improvements, not excuses. Seek respect, not attention.',
'It turns out a lot of stuff we thought was important just kinda stops existing when a lot of people stop believing it exists.',
'Honest conflict has more social value than dishonest harmony.',
'There is nothing wrong with me. I have patterns to unlearn, new behaviors to embody & wounds to heal But there is nothing wrong with the core of me & who I am. I am unlearning generations of harm and remembering love. It takes time.',
'Embrace your dreams - they’re the only way to tell sleep from death.',
'We’re all going to die, and aside from the extremely rare chance that you’ll do anything notable enough in your life, you will inevitably be forgotten, as life, the world, the universe, and everything is just a series of processes.',
'Hope is the first step on the road to disappointment.',
'Just remember, you’re unique. Just like everybody else.',
'The only thing all of your failures have in common is you.',
'Anything that can go wrong, will go wrong.',
'Life is disappointing and death inescapable.',
'If at first you don’t succeed, then try again. Then quit. No sense being a damn fool about it.',
'You’re no one’s first choice',
'The past makes you wanna die out of regret and the future makes you depressed out of anxiety. So by elimination, the present is likely the happiest time.',
'Even at your best your mind is always drifting over pointless thoughts and tomorrow you’ll hardly retain any of the great ideas you had today',
'Yeah, you’re made of star stuff, but so is garbage so calm down.',
'Nobody exists on purpose, nobody belongs anywhere, everybody’s gonna die. Come watch TV.',
'If a meme is dank, a man is not only right to repost it, he is obligated to do so. -Thomas Jefferson',
'Sometimes you gotta fail to succeed.',
'In a society that profits from your self doubt, liking yourself is a rebellious act',
'It’s ok to not be ok, but it’s not ok to not be ok and say you’re ok, ok?',
'Just because you can doesn’t mean you should',
'You are not required to set yourself on fire to keep other people warm.',
'Be the thermostat, not the thermometer.',
'Yes, it’s hard. You can do hard things.',
'Do not pray for an easy life, pray for the strength to endure a difficult one',
'Everyone you ever meet, knows something you don’t.',
'Fault is the easiest thing to find',
'Worrying is like a rocking chair, it gives you something to do but doesn’t get you anywhere.',
'If you don’t say goodbye, then you aren’t really gone. You’re just aren’t here right now.',
'Your past doesn’t define you, it just gives you the starting point of who you’re going to be.',
'Every accomplishment starts with the decision to try.',
'Isn’t it funny how day-by-day nothing changes, but when you look back everything is different',
'Find yourself a tragedy, slowly lose your Sanity.',
'They may forget what you said, but they will never forget how you made them feel.',
'well well well, if it isn’t the consequences of my own actions.',
'Be polite, be efficient and have a plan to kill everyone you meet.',
'The truth is never embarrassed by honest inquiry.',
'Just breathe',
'Life goes on.',
'You have power over your mind - not outside events. Realize this, and you will find strength.',
'The universe is change; our life is what our thoughts make it.',
'Waste no more time arguing about what a good man should be. Be one.',
'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.',
'Death smiles at us all, but all a man can do is smile back.',
'If it is not right do not do it; if it is not true do not say it.',
'It is not death that a man should fear, but he should fear never beginning to live.',
'The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.',
'The soul becomes dyed with the color of its thoughts.',
'Poverty is the mother of crime.',
'The happiness of your life depends upon the quality of your thoughts.',
'Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.',
'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.',
'When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love …',
'The best revenge is not to be like your enemy.',
'Accept the things to which fate binds you, and love the people with whom fate brings you together,but do so with all your heart.”',
'If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed.',
'I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.',
'Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize?',
'Very little is needed to make a happy life; it is all within yourself in your way of thinking.',
'Reject your sense of injury and the injury itself disappears.',
'When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly. They are like this because they can’t tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own - not of the same blood and birth, but the same mind, and possessing a share of the divine. And so none of them can hurt me. No one can implicate me in ugliness. Nor can I feel angry at my relative, or hate him. We were born to work together like feet, hands and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are unnatural.',
'When another blames you or hates you, or people voice similar criticisms, go to their souls, penetrate inside and see what sort of people they are. You will realize that there is no need to be racked with anxiety that they should hold any particular opinion about you.',
'The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.',
'Watch me take a good thing and fuck it all up in one night',
' - Machinegun Kelly',
'If you are willing to look at another person’s behavior toward you as a reflection of the state of their relationship with themselves rather than a statement about your value as a person, then you will, over a period of time cease to react at all.',
'We who lived in concentration camps can remember the men who walked through the huts comforting others, giving away their last piece of bread. they may have been few in number, but they offer sufficient proof that everything can be taken from a man but one thing: the last of the human freedoms - to choose one’s attitude in any given set of circumstances, to choose one’s own way. -Viktor E. Frankl',
'The world is full of idiots that don’t understand what’s important. - Rick Sanchez',
' I don’t like being told where to go and what to do. I consider it a violation. - Rick Sanchez',
'Nobody exists on purpose. Nobody belongs anywhere. We’re all going to die. - Morty',
'Choose to be and it will happen. If you will make a choice the answers will appear all around you.',
'There is never an excuse to be a rude, inconsiderate jerk',
'DO. NOT. SETTLE.',
'Life is much better in your own place. It’s more expensive. It’s a bit harder. But it’s yours.',
'In a house where you can’t win an argument, you learn not to talk.',
'We always talk about love as a feeling. But part of being a grown-up is learning when to express our feelings. In other words, the truth is that love, like any feeling, is a voluntary and deliberate choice.',
'You wouldn’t plant a seed and then dig it up every few minutes to see if it has grown. So why do you keep questioning yourself, your hard work and your decisions? Have patience, stop overthinking and keep watering your seeds.',
'When you continue to be irritated by someone who refuses to change, you also refuse to change.',
'Universal compassion is the only guarantee of morality.',
'Wherever you are, be there.',
'Think Positive, Feel Good.',
'Doubt kills more dreams than inability.',
'When you ask, ’why me?’ What answer would satisfy your curiosity so you’d never ask again?',
'Be excellent to each other.',
'If you’re going through hell, keep going.',
'A ship is safe in harbor, but that’s not what ships are for.',
'And with too much pride to seek therapy, they repeat and worship the same hateful teachings they absorbed as children.',
'The standard you walk past is the standard you accept.',
'There is nothing wrong with me. I have patterns to unlearn, new behaviors to embody, wounds to heal. But there is nothing wrong with the core of me & who I am. I am unlearning generations of harm and remembering love. It takes time.',
'All of us are slightly unbalanced and mad. Yet we don’t see it - and get offended if anyone dares to point it out.',
'If you want to tell people the truth, make them laugh, otherwise they’ll kill you. -George Bernard Shaw',
'The things you think about determine the quality of your mind. Your soul takes on the color of your thoughts. Marcus Aurelius',
'Stop looking for the right person, be the right person.',
'respect is a two-way street.',
'I truly appreciate any individual who spends even a mere second thinking about my well-being.',
'I like maturity: admitting where you went wrong, where i went wrong, where we went wrong; and working on it for a better outcome.',
'Don’t judge your feelings, just try to understand where they’re coming from. Judge your actions.',
'Thinking something doesn’t make it true',
'the subconscious accepts whatever thoughts you are feeding it and isn’t able to filter out if a thought is accurate or not. So it doesn’t matter if those negative thoughts about yourself are true or not, your subconscious is accepting them as reality. my entire reality is shaped by the thoughts I am choosing to give it.',
'Never expect. Never assume. Never ask. Never Demand. If it’s meant to be, it will happen.',
'"A drunk mind speaks the sober heart."',
'We know they are lying. They know they are lying. They know that we know they are lying. We know that they know that we know they are lying. And still they continue to lie.',
'you’re smart. You ask questions at an age where others choose to play games. Don’t think this a good thing from all perspectives. You’ll see more of the shit in the world than other people. It’ll be harder for you to find love, harder to tolerate injustice. Ultimately, there’s a chance you’ll be less happy than the person you call stupid. Don’t judge people. Live your life, and try to relax. Turn on your aggressive and analytical mind only when it is necessary, or you will burn out. And if you ever meet someone who you feel a connection with, a friend or more, don’t let them go. It’ll be much harder for you to replace them. People are different, most are already set on a path they will walk to their grave. Don’t try to change strangers, don’t judge them either. Waste your breath and time, on the people that matter.',
'Not everything has to makes sense. Let it go. Choose peace.',
'It’s easy for things to get away from you and create a story in your head that is very different from reality.',
'To heal my inner child i’d have to destroy capitalism.',
'Stupidity is a more dangerous enemy of the good than malice. One may protest against evil; it can be exposed and, if need be, prevented by use of force. Evil always carries within itself the germ of its own subversion in that it leaves behind in human beings at least a sense of unease. Against stupidity we are defenseless. Neither protests nor the use of force accomplish anything here; reasons fall on deaf ears; facts that contradict one’s prejudgment simply need not be believed – in such moments the stupid person even becomes critical – and when facts are irrefutable they are just pushed aside as inconsequential, as incidental. In all this the stupid person, in contrast to the malicious one, is utterly self satisfied and, being easily irritated, becomes dangerous by going on the attack. For that reason, greater caution is called for when dealing with a stupid person than with a malicious one. Never again will we try to persuade the stupid person with reasons, for it is senseless and dangerous.',
'When should you forgive someone? When they apologize properly. A proper apology has three elements. First is accepting responsibility freely and sincerely, second is doing what they can to undo the damage done, third is taking steps to see that it doesn’t happen again. If a person doesn’t do this, you can safely assume that they’ll do it again."When people show you who they really are, believe them the first time." Even if they do in fact do these things, it’s no guarantee that it won’t happen again. Do people in fact change? It’s my belief that yes they do, but rarely if ever by design. Most people are just blown on the course of their external world, and their formative experiences take them on. Most people just get older, fatter, more set in their ways, and the best of them get a little wiser. Some people however do in fact recognize that they have a say in the matter as well, and because of this, have the capacity to get better, to change, to evolve. But it is not easy. And they must do the heavy lifting, and often on their own, because their fight is truly with themselves. It is possible for people to consciously change (rather than unconsciously), but it is not likely, more the exception than the rule, and it must start with those three steps mentioned above.'

      ]} 
    />, 
    document.getElementById('quotes')
  );
  